# Generated by Django 3.1.7 on 2021-04-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Курс')),
                ('created', models.DateTimeField(auto_now=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=7000, verbose_name='Стоимость')),
                ('image', models.ImageField(upload_to='images')),
                ('draft', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Регистрация')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Номер')),
                ('email', models.CharField(max_length=200, verbose_name='Адрес')),
                ('courses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрация',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Мероприятия')),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('due', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('main_image', models.ImageField(upload_to='images')),
                ('images', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Отзыв')),
                ('descriptions', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзыв',
            },
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
