# Generated by Django 3.1.7 on 2021-04-28 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.courses', verbose_name='Курс'),
        ),
    ]
