# Generated by Django 3.1.7 on 2021-05-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_feedbacks_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('due_on', models.DateField(blank=True, verbose_name='Дата выполнения')),
                ('teacher_name', models.CharField(max_length=200, verbose_name='Имя преподавателя')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
