# Generated by Django 3.1.7 on 2021-05-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='due_on',
            field=models.DateTimeField(blank=True, verbose_name='Дата выполнения'),
        ),
    ]
